---
title: "vldmrff draft"
output: html_notebook
---



```{r first chunk}
library(tidyverse)
library(gtsummary)
library(forcats)
```
#Чтение данных

```{r}
insurance_data <- read_csv("data/HealthInsurance.csv")

insurance_data %>% 
  summary()

```
# Таблица 1

```{r}
insurance_t1_data <- insurance_data %>%
  mutate(insurance = fct_recode(insurance, "Нет страховки" = "no", "Есть страховка" = "yes")) %>% 
    mutate(
    education = fct_relevel(
      education,
      "none", "ged", "highschool", "bachelor", "master", "phd", "other"
    )
  ) %>% 
  mutate(
    education = fct_recode(
      education,
      "Нет диплома" = "none",
      "Аттестат (GED)" = "ged",
      "Средняя школа" = "highschool",
      "Бакалавр" = "bachelor",
      "Магистр" = "master",
      "Доктор наук (PhD)" = "phd",
      "Другое" = "other"
    )
  ) %>% 
  mutate(
    region = fct_recode(region,
      "Средний Запад" = "midwest",
      "Северо-восток" = "northeast",
      "Юг" = "south",
      "Запад" = "west"
    ),
    ethnicity = fct_recode(ethnicity,
      "Афроамериканцы" = "afam",
      "Европеоидные" = "cauc",
      "Другие" = "other"
    ),
    gender = fct_recode(gender,
      "Мужской" = "male",
      "Женский" = "female"
    )
  )


insurance_t1_data %>% 
  select(age,
         gender,
        ethnicity,
        region,
         married,
         family,
        health,
         limit,
         insurance,
        education,
         selfemp) %>%
  tbl_summary(
    by = insurance, # группировка
    label = list(
      age ~ "Возраст,лет",
      gender ~ "Пол",
      ethnicity ~ "Этническая группа",
      region ~ "Регион",
      married ~ "Состоит в браке",
      family ~ "Количество членов семьи",
      health ~ "Здоров по самоотчету",
      limit ~ "Есть ограничения",
      education ~ "Уровень образования",
      selfemp ~ "Самозанятый"
    ),
    statistic = list(
      all_continuous() ~ "{mean} ({sd})",
      all_categorical() ~ "{n} ({p}%)"
    ),
    missing_text = "Нет данных"
  ) %>%
  add_overall() %>%  
  bold_labels() %>%   
   modify_header(label = "Характеристика") %>%
   modify_header(
    label = "**Характеристика**",  # Жирный для характеристик
    stat_0 = "**Всего**<br>N = {N}",  # Жирный + N=
    stat_1 = "**Нет страховки**<br>N = {n}",  # Жирный + N=
    stat_2 = "**Есть страховка**<br>N = {n}"   # Жирный + N=
  ) %>%
 modify_spanning_header(
    c("stat_0", "stat_1", "stat_2") ~ "Описательные характеристики респондентов"
  )
```





